Phpt for extension running in workflow (#24)

diff --git a/.github/workflows/test-phpt.yml b/.github/workflows/test-phpt.yml
--- a/.github/workflows/test-phpt.yml
+++ b/.github/workflows/test-phpt.yml
@@ -27,8 +27,8 @@ jobs:
     with:
       build_arch: ${{ inputs.build_arch }}
 
-  build-native:
-    name: build-agent-library
+  test-phpt:
+    name: test-phpt
     runs-on: ubuntu-latest
     needs: setup-build-matrix
     timeout-minutes: 300
@@ -39,24 +39,38 @@ jobs:
       BUILD_ARCHITECTURE: ${{ matrix.arch }}
     steps:
       - uses: actions/checkout@v4
+      - uses: actions/download-artifact@v4
+        with:
+          name: build-native-${{ matrix.arch }}
+          path: prod/native/_build/${{ matrix.arch }}-release/
       - if: ${{ matrix.run_qemu }}
         uses: docker/setup-qemu-action@v3
         with:
           platforms: arm64
-      - name: Build
+      - name: Run phpt tests
         run: |
           uname -a
-          echo "Detected CPUs: $(nproc)"
-          echo "User: $(id -u):$(id -g)}"
-          echo "PWD: ${PWD}"
           echo "Arch: ${BUILD_ARCHITECTURE}"
-          docker run --rm -t -u : -v ${PWD}:/source -w /source/prod/native elasticobservability/apm-agent-php-dev:native-build-gcc-12.2.0-${BUILD_ARCHITECTURE}-0.0.2 sh -c "cmake --preset ${BUILD_ARCHITECTURE}-release  && cmake --build --preset ${BUILD_ARCHITECTURE}-release && ctest --preset ${BUILD_ARCHITECTURE}-release --verbose"
+          pushd prod/native/extension/phpt
 
+          mkdir ${PWD}/results
+
+          PHP_VERSIONS=( 80 81 82 83 )
+
+          for PHP_VERSION in "${PHP_VERSIONS[@]}"
+          do
+            ./run.sh -b ${BUILD_ARCHITECTURE} -p ${PHP_VERSION} -f ${PWD}/results/phpt-${PHP_VERSION}.tar.gz || TEST_ERROR=1
+          done
+          popd
+
+          if [ $TEST_ERROR -eq 1 ]; then
+            echo "Some tests failed"
+            exit 1
+          fi
       - uses: actions/upload-artifact@v4
+        if: failure()
         with:
-          name: build-native-${{ matrix.arch }}
+          name: test-phpt-failures-${{ matrix.arch }}
           path: |
-            prod/native/_build/${{ matrix.arch }}-release/extension/code/elastic_otel_php*.so
-            prod/native/_build/${{ matrix.arch }}-release/extension/code/elastic_otel_php*.debug
-            prod/native/_build/${{ matrix.arch }}-release/loader/code/elastic_otel_php_loader.so
-            prod/native/_build/${{ matrix.arch }}-release/loader/code/elastic_otel_php_loader.debug
+            prod/native/extension/phpt/results/*
+  
